# Generated by Django 4.2.7 on 2023-11-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mars', '0004_book_journal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Btech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('project_topic', models.TextField()),
                ('education', models.TextField()),
                ('current_designation', models.TextField(max_length=500)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('project_topic', models.TextField()),
                ('education', models.TextField()),
                ('current_designation', models.TextField(max_length=500)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Mtech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('project_topic', models.TextField()),
                ('education', models.TextField()),
                ('current_designation', models.TextField(max_length=500)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='PostDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('project_topic', models.TextField()),
                ('education', models.TextField()),
                ('current_designation', models.TextField(max_length=500)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('project_topic', models.TextField()),
                ('education', models.TextField()),
                ('current_designation', models.TextField(max_length=500)),
                ('url', models.URLField()),
            ],
        ),
    ]
