# Generated by Django 4.2.7 on 2023-11-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mars', '0005_btech_doc_mtech_postdoc_projectstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='mars'),
        ),
    ]
