# Generated by Django 4.2.7 on 2023-12-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mars', '0007_btech_image_mtech_image_projectstaff_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
        migrations.AddField(
            model_name='journal',
            name='publication_type',
            field=models.CharField(choices=[('CONF', 'Conference'), ('JRNL', 'Journal'), ('BOOK', 'Book')], default='JRNL', max_length=5),
        ),
    ]
