# Generated by Django 4.2.7 on 2023-12-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mars', '0008_delete_book_delete_publication_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('details', models.TextField()),
                ('summary', models.TextField()),
                ('researchtype', models.CharField(choices=[('og', 'ongoing'), ('comp', 'completed')], default='og', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('project_topic', models.TextField()),
                ('education', models.TextField()),
                ('current_designation', models.TextField(max_length=500)),
                ('url', models.URLField()),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('category', models.CharField(choices=[('POST', 'Postdoc'), ('DOC', 'Doc'), ('MTECH', 'Mtech'), ('BTECH', 'Btech'), ('PS', 'ProjectStaff')], default='PS', max_length=6)),
            ],
        ),
    ]
