# Generated by Django 4.2.7 on 2023-12-05 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mars', '0009_research_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostDoc',
        ),
    ]
