# Generated by Django 4.2.7 on 2023-12-05 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mars', '0010_delete_postdoc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Btech',
        ),
        migrations.DeleteModel(
            name='Doc',
        ),
        migrations.DeleteModel(
            name='Mtech',
        ),
        migrations.DeleteModel(
            name='ProjectStaff',
        ),
    ]
