# Generated by Django 4.2.7 on 2023-12-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mars', '0011_delete_btech_delete_doc_delete_mtech_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('INACTIVE', 'inactive')], default='ACTIVE', max_length=8),
        ),
    ]
