# Generated by Django 4.2.7 on 2023-12-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mars', '0014_category_eventimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='display',
            field=models.BooleanField(default=False),
        ),
    ]
