# Generated by Django 4.2.7 on 2023-12-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mars', '0016_alter_news_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='display',
            field=models.BooleanField(default=False),
        ),
    ]
