# Generated by Django 4.2.7 on 2024-01-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mars', '0017_alter_news_display'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.TextField(max_length=200)),
                ('model_name', models.TextField()),
                ('features', models.TextField()),
                ('image', models.ImageField(upload_to='infra/')),
            ],
        ),
    ]
